#!/bin/sh
# Create Runtime enviroment variables

# create env.js file
cat > /usr/share/nginx/html/env.js << EOF
window.env = {
  REACT_APP_AD_SERVICE_URL: "${REACT_APP_AD_SERVICE_URL}",
  REACT_APP_CART_SERVICE_URL: "${REACT_APP_CART_SERVICE_URL}",
  REACT_APP_CHECKOUT_SERVICE_URL: "${REACT_APP_CHECKOUT_SERVICE_URL}",
  REACT_APP_CURRENCY_SERVICE_URL: "${REACT_APP_CURRENCY_SERVICE_URL}",
  REACT_APP_PRODUCT_SERVICE_URL: "${REACT_APP_PRODUCT_SERVICE_URL}",
  REACT_APP_RECOMMENDATION_SERVICE_URL: "${REACT_APP_RECOMMENDATION_SERVICE_URL}",
  REACT_APP_SHIPPING_SERVICE_URL: "${REACT_APP_SHIPPING_SERVICE_URL}",
  REACT_APP_SHOP_BRANDING: ${REACT_APP_SHOP_BRANDING:-false},
  REACT_APP_ENABLE_ASSISTANT: ${REACT_APP_ENABLE_ASSISTANT:-false},
  REACT_APP_BASE_URL: "${REACT_APP_BASE_URL}",
  REACT_APP_DEBUG: ${REACT_APP_DEBUG:-false}
};
EOF

# Start nginx
exec "$@"